In [1]:
import requests
from IPython.core.display import HTML
HTML(f"""
<style>
@import "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css";
</style>
""")

# Linear Algebra
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy. The following topics will be covered:
- Performing matrix operations (elementwise operations, transpose, multiplication, inverse).
- Properties of matrix multiplication and inverse.
- Representing linear equations in matrix form.
- Solving linear equations using the matrix inverse.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication - Hadamard pr…</a>
            </li>
            <li>
            <a href="#inverses">Task 4: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 5: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 6: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 7: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 8: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 9: Implementing matrix multiplication</a>
            </li>
            <li>
            <a href="#extra">Task 10: Extra exercises</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)

## Matrix Operations
<article class="message task"><a class="anchor" id="diff"></a>
    <div class="message-header">
        <span>Task 1: Elementwise difference</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $A-B$ in the code cell below.



</div></article>



In [6]:
# Write your solution here
def ElementwiseDifference(a,b):
    print("a - b is :  \n",
           a - b)

ElementwiseDifference(A,B)

a - b is :  
 [[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]


<article class="message task"><a class="anchor" id="mul_prop"></a>
    <div class="message-header">
        <span>Task 2: Multiplication properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).
2. Explain why the results are different.



</div></article>



In [11]:
#np.set_printoptions(precision=3) change floating point precision in the notebook
# Write your solution here
def multiplicaiton_dot(a,b):
    print(np.dot(a,b))

def multiplication_weird(a,b):
    print(a@b)

print("dot")
multiplicaiton_dot(A,C)
multiplicaiton_dot(C,A)

print("@")
multiplication_weird(A,C)
multiplication_weird(C,A)

#AC vs CA is different because ordering does matter when multiplicating vectors. Think about shear then inverse and inverse then shear. 


dot
[[1.424 0.769 0.537 0.415]
 [0.8   0.44  0.311 0.242]
 [0.567 0.314 0.223 0.174]
 [0.441 0.245 0.175 0.137]]
[[1.424 0.8   0.567 0.441]
 [0.8   0.464 0.333 0.262]
 [0.509 0.291 0.208 0.163]
 [0.391 0.226 0.163 0.128]]
@
[[1.424 0.769 0.537 0.415]
 [0.8   0.44  0.311 0.242]
 [0.567 0.314 0.223 0.174]
 [0.441 0.245 0.175 0.137]]
[[1.424 0.8   0.567 0.441]
 [0.8   0.464 0.333 0.262]
 [0.509 0.291 0.208 0.163]
 [0.391 0.226 0.163 0.128]]
*
[[1.424 0.769 0.537 0.415]
 [0.8   0.44  0.311 0.242]
 [0.567 0.314 0.223 0.174]
 [0.441 0.245 0.175 0.137]]
[[1.    0.25  0.111 0.062]
 [0.25  0.111 0.062 0.04 ]
 [0.111 0.05  0.029 0.019]
 [0.062 0.029 0.021 0.016]]


<article class="message task"><a class="anchor" id="elem_mul"></a>
    <div class="message-header">
        <span>Task 3: Elementwise multiplication - Hadamard product</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators.



</div></article>



In [12]:
# Write your solution here


def multiplication_maybe(a,b):
    print(a*b)


print("*")
multiplication_weird(A,C)
multiplication_maybe(C,A)

# * is elementwise, so we say cell 1 times cell 2.. all the way to the end
# @ and dot are the same, they are vector multiplication which is what we usually want, otherwise we're not switching the vector as expected. 

*
[[1.424 0.769 0.537 0.415]
 [0.8   0.44  0.311 0.242]
 [0.567 0.314 0.223 0.174]
 [0.441 0.245 0.175 0.137]]
[[1.    0.25  0.111 0.062]
 [0.25  0.111 0.062 0.04 ]
 [0.111 0.05  0.029 0.019]
 [0.062 0.029 0.021 0.016]]


<article class="message task"><a class="anchor" id="inverses"></a>
    <div class="message-header">
        <span>Task 4: Inverses</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. 

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">

  The question relates to the limitations of floating point numbers.


  </div>
</article>


</div></article>



In [35]:
# Write your solution here

def inverse(a):
    return np.linalg.inv(a)

inv = inverse(A)

print("A")
print(A)
print(f'inverse is\n {inv}\n')
print(A@inv)
print(inv@A@inv)


print("C")
inv2 = inverse(C)
print(f'{inv2}\n')
print(C@inv2)


#we can see that A@(A@A_inv) == inv.. also if we round the result of A A_I we can also see thats its just floating point numbers acting up


A
[[1.    0.5   0.333 0.25 ]
 [0.5   0.333 0.25  0.2  ]
 [0.333 0.25  0.2   0.167]
 [0.25  0.2   0.167 0.143]]
inverse is
 [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]

[[ 1.000e+00  0.000e+00  2.274e-13  0.000e+00]
 [-1.554e-15  1.000e+00  1.125e-13  3.109e-14]
 [ 1.295e-15 -3.449e-14  1.000e+00 -4.485e-14]
 [-5.995e-15  8.006e-14 -1.616e-13  1.000e+00]]
[[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
C
[[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]

[[ 1.000e+00  2.274e-13  0.000e+00  5.684e-14]
 [ 2.998e-14  1.000e+00 -2.098e-13  2.580e-14]
 [-6.718e-14 -1.115e-13  1.000e+00  5.198e-14]
 [-1.034e-14  2.233e-15  1.671e-13  1.000e+00]]


## Properties
<article class="message task"><a class="anchor" id="inverse_prop"></a>
    <div class="message-header">
        <span>Task 5: Inverse properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$



</div></article>



In [42]:
# Write your solution here

D_I = inverse(D)
E_I = inverse(E)
ED_I = inverse((E@D))
DE_I = inverse((D@E))

print(D_I@E_I)
print(ED_I)
print("")

print(D_I@E_I)
print(DE_I)

[[ 0.253  0.136 -0.513]
 [-0.086  0.115  0.185]
 [ 0.166 -0.19   0.178]]
[[ 0.253  0.136 -0.513]
 [-0.086  0.115  0.185]
 [ 0.166 -0.19   0.178]]

[[ 0.253  0.136 -0.513]
 [-0.086  0.115  0.185]
 [ 0.166 -0.19   0.178]]
[[ 0.211 -0.256 -0.152]
 [-0.154  0.206  0.566]
 [ 0.054 -0.283  0.128]]


<article class="message task"><a class="anchor" id="determinant"></a>
    <div class="message-header">
        <span>Task 6: The determinant</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Determine which of the matrices $A,B,C$ have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-7>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).



</div></article>



In [44]:
# Write your solution here

def determinant(M):
    return np.linalg.det(M)

A_det = determinant(A)
B_det = determinant(B)
C_det = determinant(D)

print(A_det)
print(B_det)
print(C_det)

1.6534391534390412e-07
0.0
11.812500000000004


<article class="message task"><a class="anchor" id="transpose"></a>
    <div class="message-header">
        <span>Task 7: Transpose</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.

  
  </div>
</article>



</div></article>



In [48]:
# Write your solution here
print(D,'\n', D.T)
print(D_I)
fst = np.transpose(D_I)
snd = inverse(np.transpose(D))

print(fst == snd) 


[[ 2.    4.    2.5 ]
 [-0.75  2.    0.25]
 [ 0.25  0.5   2.  ]] 
 [[ 2.   -0.75  0.25]
 [ 4.    2.    0.5 ]
 [ 2.5   0.25  2.  ]]
[[ 0.328 -0.571 -0.339]
 [ 0.132  0.286 -0.201]
 [-0.074  0.     0.593]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ vector of unknowns, and $b$ is a vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$
<article class="message task"><a class="anchor" id="eqsys"></a>
    <div class="message-header">
        <span>Task 8: Solving linear equation systems</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse. Your answers have to be submitted in [Grasple](https://app.grasple.com/#/courses/10532/ci/733997/diagnoses/12886)
:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$


</div></article>



In [0]:
# Write your solutions here



## Matrix multiplication
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is a new $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.
<article class="message task"><a class="anchor" id="matmul"></a>
    <div class="message-header">
        <span>Task 9: Implementing matrix multiplication</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's built-in functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.
<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  It might be helpful to calculate the correct result by hand first, to make debugging easier.

  
  </div>
</article>



</div></article>



In [0]:
def matmul(a, b):
    # Implement this function
    ...
    

ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

matmul(ma, mb)

<article class="message task"><a class="anchor" id="extra"></a>
    <div class="message-header">
        <span>Task 10: Extra exercises</span>
        <span class="has-text-right">
          <i class="bi bi-lightbulb-fill"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Additional exercises are available on Grasple. Complete these if you need more practice with fundamental linear algebra operations and properties:
1. [Matrix Operations](https://app.grasple.com/#/courses/10532/ci/694300/subjects/3936)

2. [Addition, Scalar Multiplication and Transposition](https://app.grasple.com/#/courses/10532/ci/694301/subjects/3935)

3. [Inverse Matrices](https://app.grasple.com/#/courses/10532/ci/735682/subjects/3939)




</div></article>

---
